import { Movie, Place } from '../types';

export const FAKE_MOVIES: Movie[] = [
  {
    id: 'fake-movie-1',
    title: 'Inception',
    addedBy: 'Aaron',
    watchedBy: ['Aaron', 'Electra'],
    createdAt: '2023-01-01T00:00:00.000Z',
    year: '2010',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg',
    plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    imdbRating: '8.8',
    runtime: '148 min',
    genre: 'Action, Adventure, Sci-Fi',
    director: 'Christopher Nolan',
  },
  {
    id: 'fake-movie-2',
    title: 'The Matrix',
    addedBy: 'Electra',
    watchedBy: ['Aaron'],
    createdAt: '2023-02-15T00:00:00.000Z',
    year: '1999',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    plot: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    imdbRating: '8.7',
    runtime: '136 min',
    genre: 'Action, Sci-Fi',
    director: 'Lana Wachowski, Lilly Wachowski',
  },
  {
    id: 'fake-movie-3',
    title: 'Interstellar',
    addedBy: 'Aaron',
    watchedBy: [],
    createdAt: '2023-03-10T00:00:00.000Z',
    year: '2014',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    plot: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    imdbRating: '8.6',
    runtime: '169 min',
    genre: 'Adventure, Drama, Sci-Fi',
    director: 'Christopher Nolan',
  },
  {
    id: 'fake-movie-4',
    title: 'Parasite',
    addedBy: 'Electra',
    watchedBy: [],
    createdAt: '2023-04-05T00:00:00.000Z',
    year: '2019',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg',
    plot: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    imdbRating: '8.6',
    runtime: '132 min',
    genre: 'Drama, Thriller',
    director: 'Bong Joon Ho',
  },
  {
    id: 'fake-movie-5',
    title: 'Spirited Away',
    addedBy: 'Aaron',
    watchedBy: ['Electra'],
    createdAt: '2023-05-20T00:00:00.000Z',
    year: '2001',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    plot: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    imdbRating: '8.6',
    runtime: '125 min',
    genre: 'Animation, Adventure, Family',
    director: 'Hayao Miyazaki',
  },
  {
    id: 'fake-movie-6',
    title: 'The Grand Budapest Hotel',
    addedBy: 'Electra',
    watchedBy: ['Aaron', 'Electra'],
    createdAt: '2023-06-15T00:00:00.000Z',
    year: '2014',
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg',
    plot: 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
    imdbRating: '8.1',
    runtime: '99 min',
    genre: 'Adventure, Comedy, Crime',
    director: 'Wes Anderson',
  }
];

export const FAKE_PLACES: Place[] = [
  {
    id: 'fake-place-1',
    name: 'Kyoto, Japan',
    addedBy: 'Aaron',
    notes: 'Visit the Fushimi Inari Shrine and Kinkaku-ji.',
    createdAt: '2023-01-10T00:00:00.000Z',
    visitedAt: '2023-11-15T00:00:00.000Z',
  },
  {
    id: 'fake-place-2',
    name: 'Santorini, Greece',
    addedBy: 'Electra',
    notes: 'Watch the sunset in Oia.',
    createdAt: '2023-02-20T00:00:00.000Z',
  },
  {
    id: 'fake-place-3',
    name: 'Banff National Park, Canada',
    addedBy: 'Aaron',
    notes: 'Hiking and canoeing on Lake Louise.',
    createdAt: '2023-03-05T00:00:00.000Z',
  },
  {
    id: 'fake-place-4',
    name: 'Machu Picchu, Peru',
    addedBy: 'Electra',
    notes: 'Inca trail trek.',
    createdAt: '2023-04-12T00:00:00.000Z',
  }
];
