// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fish-tank/FishTank.tsx": () => import("../components/mockups/fish-tank/FishTank.tsx"),
  "./components/mockups/movie-card/AccessFirst.tsx": () => import("../components/mockups/movie-card/AccessFirst.tsx"),
  "./components/mockups/movie-card/AffordanceFirst.tsx": () => import("../components/mockups/movie-card/AffordanceFirst.tsx"),
  "./components/mockups/movie-card/HierarchyFirst.tsx": () => import("../components/mockups/movie-card/HierarchyFirst.tsx"),
  "./components/mockups/movie-night-minimal/CleanLight.tsx": () => import("../components/mockups/movie-night-minimal/CleanLight.tsx"),
  "./components/mockups/movie-night-minimal/DarkMinimal.tsx": () => import("../components/mockups/movie-night-minimal/DarkMinimal.tsx"),
  "./components/mockups/movie-night-minimal/WarmNeutral.tsx": () => import("../components/mockups/movie-night-minimal/WarmNeutral.tsx"),
  "./components/mockups/quiz-internet-ad/InternetAdQuiz.tsx": () => import("../components/mockups/quiz-internet-ad/InternetAdQuiz.tsx"),
  "./components/mockups/workspace-reimagine/Atmospheric.tsx": () => import("../components/mockups/workspace-reimagine/Atmospheric.tsx"),
  "./components/mockups/workspace-reimagine/BrutalistCinema.tsx": () => import("../components/mockups/workspace-reimagine/BrutalistCinema.tsx"),
  "./components/mockups/workspace-reimagine/Calibrated.tsx": () => import("../components/mockups/workspace-reimagine/Calibrated.tsx"),
  "./components/mockups/workspace-reimagine/MidnightCinema.tsx": () => import("../components/mockups/workspace-reimagine/MidnightCinema.tsx"),
  "./components/mockups/workspace-reimagine/MoireBlend.tsx": () => import("../components/mockups/workspace-reimagine/MoireBlend.tsx"),
  "./components/mockups/workspace-reimagine/NeonNoir.tsx": () => import("../components/mockups/workspace-reimagine/NeonNoir.tsx"),
  "./components/mockups/workspace-reimagine/SoftEditorial.tsx": () => import("../components/mockups/workspace-reimagine/SoftEditorial.tsx"),
  "./components/mockups/workspace-reimagine/UnifiedPanel.tsx": () => import("../components/mockups/workspace-reimagine/UnifiedPanel.tsx")
};
